# App name
spring.application.name=approvalhub

# Url database postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.application.name}

# Credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate/JPA configuration
spring.jpa.hibernate.ddl-auto=create

# Show sql console
spring.jpa.show-sql=true

# Logs config
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Jwt auth
app.secret-key=BzFAO8PDgTKt/X+noUUMa+MqLmMGtTjOVSyZMj9CZ0M=
app.expiration-time=900000

# Kafka
# Adresse des brokers Kafka (cluster)
spring.kafka.bootstrap-servers=localhost:9092
# Topics custom
app.kafka.topics=document-status-events
# Configuration du consumer
spring.kafka.consumer.group-id=approvalhub
spring.kafka.consumer.auto-offset-reset=earliest
# Sérialisation des clés en String
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Enveloppe les valeurs dans un désérialiseur qui gère les erreurs proprement
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# Dit au ErrorHandlingDeserializer quel désérialiseur utiliser (JsonDeserializer)
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
# Dit au JsonDeserializer de faire confiance à tous les packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Indique au JsonDeserializer la classe dans laquelle il doit convertir le json
spring.kafka.consumer.properties.spring.json.value.default.type=com.approvalhub.dto.status.DocumentStatusEvent
# Configuration du producer
# Sérialisation des clés en String
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Sérialisation des valeurs en JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ElasticSearch
# url serveur
spring.elasticsearch.uris=http://localhost:9200
# Credentials
spring.elasticsearch.username=elastic
spring.elasticsearch.password=elastic
spring.elasticsearch.ssl.verification-mode=none
org.springframework.data.elasticsearch=DEBUG


